kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: carts-db-route
  labels:
    name: carts-db
spec:
  to:
    kind: Service
    name: carts-db
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None